name: Documentation Improvement
description: Report wrong or missing documentation
type: "Documentation improvement"

body:
  - type: textarea
    id: problem
    attributes:
      label: Documentation problem
      description: >
        Please provide a description of what you believe needs to be fixed/ improved/ explained.
    validations:
      required: true
  - type: textarea
    id: location
    attributes:
      label: Location
      description: >
        Please provide the location where should be improved or created.
    validations:
      required: true
