name: Install software from PyPI (uv optimized) and run tests

on:
  workflow_call:
    inputs:
      runner_tag:
        description: "Tag of the runner that should be run"
        required: true
        type: string
      python_version:
        description: "Python version which should be used to setup the environment"
        required: true
        type: string
      library_name:
        description: "Name of the library which should be installed for a specific version"
        default: ""
        required: false
        type: string
      library_version:
        description: "Version of the library that should be installed"
        required: false
        type: string
      optional_dependency_PyPI_tag:
        description: "Additional string that is placed after the dot of uv pip install"
        required: false
        default: ""
        type: string
      ipynb_example_folder:
        description: "Name of folder which contains ipynb examples that should be executed as a test"
        default: "No Example Folder"
        required: false
        type: string
      examples_to_execute:
        description: "Relative path string of examples that should be executed"
        default: "No Examples"
        required: false
        type: string
      multiprocessing_example_string:
        description: "String to be included to execute examples with multiprocessing. -n auto for automatic determination of runners, -n 2 for two runner 2 -n 3 for 3 runner ..."
        default: ""
        required: false
        type: string
      multiprocessing_pytest_string:
        description: "String to use multiprocessing in pytest. -n auto for automatic determination of runners, -n 2 for two runner 2 -n 3 for 3 runner ..."
        default: ""
        required: false
        type: string
      lfs:
        description: "Whether to checkout with Git LFS"
        default: false
        required: false
        type: boolean

defaults:
  run:
    shell: pwsh

jobs:
  run-pypi-test:
    name: "Run test for ${{ inputs.library_name }}=${{ inputs.library_version }} on ${{ inputs.runner_tag }}"
    runs-on: ${{ inputs.runner_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: ${{ inputs.lfs }}
      - name: Install uv and Python
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ inputs.python_version }}
      - name: Create virtual environment
        run: uv venv .venv --python ${{ inputs.python_version }}
      - name: Add venv to PATH
        run: |
          "${{ github.workspace }}\.venv\Scripts" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
          "VIRTUAL_ENV=${{ github.workspace }}\.venv" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      - name: Setup Environment PyPI without additional dependencies
        if: ${{ inputs.library_name == '' }}
        run: |
          ls
          uv pip install .${{ inputs.optional_dependency_PyPI_tag }}
          echo "uv pip installation is done"
          uv pip list
          echo "All dependencies are shown"
          uv pip check
          echo "Checked for dependency conflicts"
      - name: Setup Environment PyPI with additional dependencies
        if: ${{ inputs.library_name != '' }}
        run: |
          ls
          uv pip install .${{ inputs.optional_dependency_PyPI_tag }} "${{ inputs.library_name }}==${{ inputs.library_version }}"
          echo "uv pip installation is done"
          uv pip list
          echo "All dependencies are shown"
          uv pip check
          echo "Checked for dependency conflicts"
      - name: Run Pytest
        run: |
          echo "start pytest"
          pytest ${{ inputs.multiprocessing_pytest_string }} -vv
          echo "Pytest done"
      - name: Run all Examples PyPI
        if: ${{ inputs.ipynb_example_folder != 'No Example Folder' }}
        run: |
          python -m pytest ${{ inputs.multiprocessing_example_string }} -vv --dist loadscope --nbval-lax --nbval-current-env --nbval-cell-timeout=900000 --durations=20 ${{ inputs.ipynb_example_folder }}/
      - name: Run Selected Examples PyPI
        if: ${{ inputs.examples_to_execute != 'No Examples' }}
        run: |
          python -m pytest ${{ inputs.multiprocessing_example_string }} -vv --dist loadscope --nbval-lax --nbval-current-env --nbval-cell-timeout=900000 --durations=20 ${{ inputs.examples_to_execute }}
